import { Student, Instructor, Lesson, Exam, Payment, Vehicle, Package, Sale, AccountsReceivable, AccountsPayable, Supplier, User, Role } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Administrador Sistema',
    email: 'admin@autoescola.com',
    password: 'admin123',
    role: 'admin',
    status: 'active',
    createdDate: '2024-01-01',
    permissions: [], // Admin tem acesso total
  },
  {
    id: '2',
    name: 'João Vendedor',
    email: 'vendedor@autoescola.com',
    password: 'vendedor123',
    role: 'seller',
    status: 'active',
    createdDate: '2024-01-15',
    permissions: [
      { module: 'students', actions: ['view', 'create', 'edit'] },
      { module: 'packages', actions: ['view'] },
      { module: 'sales', actions: ['view', 'create'] },
      { module: 'dashboard', actions: ['view'] },
      { module: 'schedule', actions: ['view'] },
    ],
  },
  {
    id: '3',
    name: 'Maria Financeiro',
    email: 'financeiro@autoescola.com',
    password: 'financeiro123',
    role: 'financial',
    status: 'active',
    createdDate: '2024-01-20',
    permissions: [
      { module: 'financial', actions: ['view', 'create', 'edit', 'delete'] },
      { module: 'sales', actions: ['view'] },
      { module: 'students', actions: ['view'] },
      { module: 'dashboard', actions: ['view'] },
    ],
  },
  {
    id: '4',
    name: 'Carlos Instrutor',
    email: 'instrutor@autoescola.com',
    password: 'instrutor123',
    role: 'instructor',
    status: 'active',
    createdDate: '2024-02-01',
    permissions: [
      { module: 'lessons', actions: ['view', 'create', 'edit'] },
      { module: 'students', actions: ['view'] },
      { module: 'exams', actions: ['view', 'edit'] },
      { module: 'dashboard', actions: ['view'] },
      { module: 'schedule', actions: ['view'] },
    ],
  },
  {
    id: '5',
    name: 'Ana Gerente',
    email: 'gerente@autoescola.com',
    password: 'gerente123',
    role: 'manager',
    status: 'active',
    createdDate: '2024-01-10',
    permissions: [
      { module: 'students', actions: ['view', 'create', 'edit', 'delete'] },
      { module: 'instructors', actions: ['view', 'create', 'edit'] },
      { module: 'vehicles', actions: ['view', 'create', 'edit'] },
      { module: 'lessons', actions: ['view', 'create', 'edit'] },
      { module: 'exams', actions: ['view', 'create', 'edit'] },
      { module: 'packages', actions: ['view', 'create', 'edit'] },
      { module: 'sales', actions: ['view'] },
      { module: 'financial', actions: ['view'] },
      { module: 'dashboard', actions: ['view'] },
      { module: 'schedule', actions: ['view'] },
    ],
  },
];

export const mockRoles: Role[] = [
  {
    id: 'admin',
    name: 'Administrador',
    description: 'Acesso total ao sistema',
    color: 'purple',
    permissions: [], // Admin tem acesso total
  },
  {
    id: 'manager',
    name: 'Gerente',
    description: 'Gerenciamento geral da auto escola',
    color: 'blue',
    permissions: [
      { module: 'students', actions: ['view', 'create', 'edit', 'delete'] },
      { module: 'instructors', actions: ['view', 'create', 'edit'] },
      { module: 'vehicles', actions: ['view', 'create', 'edit'] },
      { module: 'lessons', actions: ['view', 'create', 'edit'] },
      { module: 'exams', actions: ['view', 'create', 'edit'] },
      { module: 'packages', actions: ['view', 'create', 'edit'] },
      { module: 'sales', actions: ['view'] },
      { module: 'financial', actions: ['view'] },
      { module: 'dashboard', actions: ['view'] },
      { module: 'schedule', actions: ['view'] },
    ],
  },
  {
    id: 'seller',
    name: 'Vendedor',
    description: 'Vendas e atendimento ao cliente',
    color: 'green',
    permissions: [
      { module: 'students', actions: ['view', 'create', 'edit'] },
      { module: 'packages', actions: ['view'] },
      { module: 'sales', actions: ['view', 'create'] },
      { module: 'dashboard', actions: ['view'] },
      { module: 'schedule', actions: ['view'] },
    ],
  },
  {
    id: 'financial',
    name: 'Financeiro',
    description: 'Controle financeiro e contabilidade',
    color: 'yellow',
    permissions: [
      { module: 'financial', actions: ['view', 'create', 'edit', 'delete'] },
      { module: 'sales', actions: ['view'] },
      { module: 'students', actions: ['view'] },
      { module: 'dashboard', actions: ['view'] },
    ],
  },
  {
    id: 'instructor',
    name: 'Instrutor',
    description: 'Agendamento de aulas e avaliações',
    color: 'orange',
    permissions: [
      { module: 'lessons', actions: ['view', 'create', 'edit'] },
      { module: 'students', actions: ['view'] },
      { module: 'exams', actions: ['view', 'edit'] },
      { module: 'dashboard', actions: ['view'] },
      { module: 'schedule', actions: ['view'] },
    ],
  },
  {
    id: 'receptionist',
    name: 'Recepcionista',
    description: 'Atendimento e cadastros básicos',
    color: 'pink',
    permissions: [
      { module: 'students', actions: ['view', 'create', 'edit'] },
      { module: 'lessons', actions: ['view'] },
      { module: 'dashboard', actions: ['view'] },
      { module: 'schedule', actions: ['view'] },
    ],
  },
];

export const mockStudents: Student[] = [
  {
    id: '1',
    name: 'Maria Silva Santos',
    email: 'maria.silva@email.com',
    phone: '(11) 99999-9999',
    cpf: '123.456.789-01',
    birthDate: '1995-03-15',
    address: 'Rua das Flores, 123 - São Paulo, SP',
    category: 'B',
    status: 'active',
    registrationDate: '2024-01-15',
    theoreticalHours: 35,
    practicalHours: 18,
  },
  {
    id: '2',
    name: 'João Pedro Costa',
    email: 'joao.costa@email.com',
    phone: '(11) 88888-8888',
    cpf: '987.654.321-02',
    birthDate: '1988-07-22',
    address: 'Av. Paulista, 456 - São Paulo, SP',
    category: 'B',
    status: 'active',
    registrationDate: '2024-02-01',
    theoreticalHours: 45,
    practicalHours: 25,
  },
  {
    id: '3',
    name: 'Ana Carolina Lima',
    email: 'ana.lima@email.com',
    phone: '(11) 77777-7777',
    cpf: '456.789.123-03',
    birthDate: '2000-11-08',
    address: 'Rua Augusta, 789 - São Paulo, SP',
    category: 'A',
    status: 'active',
    registrationDate: '2024-01-20',
    theoreticalHours: 40,
    practicalHours: 12,
  },
];

export const mockInstructors: Instructor[] = [
  {
    id: '1',
    name: 'Carlos Eduardo Mendes',
    email: 'carlos.mendes@autoescola.com',
    phone: '(11) 99999-1111',
    cpf: '111.222.333-44',
    license: 'SP123456789',
    specialties: ['Categoria B', 'Categoria C'],
    status: 'active',
    workingHours: {
      start: '08:00',
      end: '18:00',
      days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
    }
  },
  {
    id: '2',
    name: 'Patrícia Oliveira Santos',
    email: 'patricia.santos@autoescola.com',
    phone: '(11) 88888-2222',
    cpf: '222.333.444-55',
    license: 'SP987654321',
    specialties: ['Categoria A', 'Categoria B'],
    status: 'active',
    workingHours: {
      start: '07:00',
      end: '17:00',
      days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
    }
  },
  {
    id: '3',
    name: 'Roberto Silva Ferreira',
    email: 'roberto.ferreira@autoescola.com',
    phone: '(11) 77777-3333',
    cpf: '333.444.555-66',
    license: 'SP456789123',
    specialties: ['Categoria B', 'Categoria D'],
    status: 'active',
    workingHours: {
      start: '13:00',
      end: '22:00',
      days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
    }
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    brand: 'Volkswagen',
    model: 'Gol',
    year: 2022,
    plate: 'ABC-1234',
    category: 'B',
    status: 'available',
    fuelType: 'flex',
    transmission: 'manual',
    color: 'Branco',
    registrationDate: '2022-01-15',
  },
  {
    id: '2',
    brand: 'Chevrolet',
    model: 'Onix',
    year: 2023,
    plate: 'DEF-5678',
    category: 'B',
    status: 'available',
    fuelType: 'flex',
    transmission: 'automatic',
    color: 'Prata',
    registrationDate: '2023-03-10',
  },
  {
    id: '3',
    brand: 'Honda',
    model: 'CG 160',
    year: 2021,
    plate: 'GHI-9012',
    category: 'A',
    status: 'available',
    fuelType: 'gasoline',
    transmission: 'manual',
    color: 'Vermelho',
    registrationDate: '2021-08-20',
  },
  {
    id: '4',
    brand: 'Ford',
    model: 'Cargo 816',
    year: 2020,
    plate: 'JKL-3456',
    category: 'C',
    status: 'maintenance',
    fuelType: 'diesel',
    transmission: 'manual',
    color: 'Azul',
    registrationDate: '2020-05-12',
  },
];

export const mockLessons: Lesson[] = [
  {
    id: '1',
    studentId: '1',
    instructorId: '1',
    vehicleId: '1',
    type: 'practical',
    date: '2024-02-15',
    time: '14:00',
    duration: 50,
    status: 'scheduled',
    location: 'Centro de Treinamento',
  },
  {
    id: '2',
    studentId: '2',
    instructorId: '2',
    type: 'theoretical',
    date: '2024-02-16',
    time: '09:00',
    duration: 50,
    status: 'completed',
    location: 'Sala de Aula 1',
  },
  {
    id: '3',
    studentId: '3',
    instructorId: '2',
    vehicleId: '3',
    type: 'practical',
    date: '2024-02-17',
    time: '10:00',
    duration: 50,
    status: 'scheduled',
    location: 'Pista de Treinamento',
  },
  {
    id: '4',
    studentId: '1',
    instructorId: '1',
    vehicleId: '1',
    type: 'practical',
    date: '2024-02-19',
    time: '15:00',
    duration: 50,
    status: 'scheduled',
    location: 'Centro de Treinamento',
  },
  {
    id: '5',
    studentId: '2',
    instructorId: '1',
    vehicleId: '2',
    type: 'practical',
    date: '2024-02-20',
    time: '16:00',
    duration: 50,
    status: 'scheduled',
    location: 'Centro de Treinamento',
  },
];

export const mockExams: Exam[] = [
  {
    id: '1',
    studentId: '1',
    type: 'theoretical',
    date: '2024-02-20',
    time: '10:00',
    status: 'scheduled',
    attempts: 1,
  },
  {
    id: '2',
    studentId: '2',
    type: 'practical',
    date: '2024-02-22',
    time: '15:00',
    status: 'approved',
    score: 85,
    attempts: 1,
  },
];

export const mockPayments: Payment[] = [
  {
    id: '1',
    studentId: '1',
    amount: 1200,
    type: 'enrollment',
    status: 'paid',
    dueDate: '2024-01-15',
    paidDate: '2024-01-15',
  },
  {
    id: '2',
    studentId: '1',
    amount: 400,
    type: 'monthly',
    status: 'pending',
    dueDate: '2024-02-15',
  },
];

export const mockPackages: Package[] = [
  {
    id: '1',
    name: 'Pacote Categoria B - Básico',
    description: 'Pacote completo para primeira habilitação categoria B',
    category: 'B',
    price: 1800,
    theoreticalHours: 45,
    practicalHours: 20,
    examAttempts: 2,
    validityDays: 365,
    status: 'active',
    createdDate: '2024-01-01',
  },
  {
    id: '2',
    name: 'Pacote Categoria B - Premium',
    description: 'Pacote premium com aulas extras e simulados',
    category: 'B',
    price: 2500,
    theoreticalHours: 50,
    practicalHours: 30,
    examAttempts: 3,
    validityDays: 450,
    status: 'active',
    createdDate: '2024-01-01',
  },
  {
    id: '3',
    name: 'Pacote Categoria A - Completo',
    description: 'Pacote para habilitação de motocicleta',
    category: 'A',
    price: 1500,
    theoreticalHours: 45,
    practicalHours: 20,
    examAttempts: 2,
    validityDays: 365,
    status: 'active',
    createdDate: '2024-01-01',
  },
  {
    id: '4',
    name: 'Pacote Categoria C - Caminhão',
    description: 'Adição de categoria C para caminhões',
    category: 'C',
    price: 2200,
    theoreticalHours: 50,
    practicalHours: 25,
    examAttempts: 2,
    validityDays: 365,
    status: 'active',
    createdDate: '2024-01-01',
  },
];

export const mockSales: Sale[] = [
  {
    id: '1',
    studentId: '1',
    packageId: '1',
    saleDate: '2024-01-15',
    totalAmount: 1800,
    discount: 100,
    finalAmount: 1700,
    paymentMethod: 'installments',
    installments: 6,
    status: 'completed',
    notes: 'Desconto por indicação',
    sellerId: '2',
  },
  {
    id: '2',
    studentId: '2',
    packageId: '2',
    saleDate: '2024-02-01',
    totalAmount: 2500,
    discount: 0,
    finalAmount: 2500,
    paymentMethod: 'pix',
    status: 'completed',
    sellerId: '2',
  },
  {
    id: '3',
    studentId: '3',
    packageId: '3',
    saleDate: '2024-01-20',
    totalAmount: 1500,
    discount: 50,
    finalAmount: 1450,
    paymentMethod: 'installments',
    installments: 4,
    status: 'completed',
    sellerId: '2',
  },
];

export const mockAccountsReceivable: AccountsReceivable[] = [
  {
    id: '1',
    saleId: '1',
    studentId: '1',
    description: 'Pacote Categoria B - Básico (1/6)',
    amount: 283.33,
    dueDate: '2024-01-15',
    status: 'paid',
    paymentDate: '2024-01-15',
    paymentMethod: 'pix',
    installmentNumber: 1,
    totalInstallments: 6,
  },
  {
    id: '2',
    saleId: '1',
    studentId: '1',
    description: 'Pacote Categoria B - Básico (2/6)',
    amount: 283.33,
    dueDate: '2024-02-15',
    status: 'pending',
    installmentNumber: 2,
    totalInstallments: 6,
  },
  {
    id: '3',
    saleId: '1',
    studentId: '1',
    description: 'Pacote Categoria B - Básico (3/6)',
    amount: 283.33,
    dueDate: '2024-03-15',
    status: 'pending',
    installmentNumber: 3,
    totalInstallments: 6,
  },
  {
    id: '4',
    saleId: '2',
    studentId: '2',
    description: 'Pacote Categoria B - Premium',
    amount: 2500,
    dueDate: '2024-02-01',
    status: 'paid',
    paymentDate: '2024-02-01',
    paymentMethod: 'pix',
  },
  {
    id: '5',
    saleId: '3',
    studentId: '3',
    description: 'Pacote Categoria A - Completo (1/4)',
    amount: 362.50,
    dueDate: '2024-01-20',
    status: 'paid',
    paymentDate: '2024-01-20',
    paymentMethod: 'credit_card',
    installmentNumber: 1,
    totalInstallments: 4,
  },
  {
    id: '6',
    saleId: '3',
    studentId: '3',
    description: 'Pacote Categoria A - Completo (2/4)',
    amount: 362.50,
    dueDate: '2024-02-20',
    status: 'pending',
    installmentNumber: 2,
    totalInstallments: 4,
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'Posto Ipiranga Centro',
    cnpj: '12.345.678/0001-90',
    email: 'contato@postipiranga.com',
    phone: '(11) 3333-4444',
    address: 'Av. Paulista, 1000 - São Paulo, SP',
    category: 'fuel',
    status: 'active',
    registrationDate: '2024-01-01',
  },
  {
    id: '2',
    name: 'Oficina do João',
    cnpj: '98.765.432/0001-10',
    email: 'joao@oficina.com',
    phone: '(11) 2222-3333',
    address: 'Rua das Oficinas, 456 - São Paulo, SP',
    category: 'maintenance',
    status: 'active',
    registrationDate: '2024-01-01',
  },
  {
    id: '3',
    name: 'Papelaria Escolar',
    cnpj: '11.222.333/0001-44',
    email: 'vendas@papelaria.com',
    phone: '(11) 1111-2222',
    address: 'Rua do Comércio, 789 - São Paulo, SP',
    category: 'supplies',
    status: 'active',
    registrationDate: '2024-01-01',
  },
];

export const mockAccountsPayable: AccountsPayable[] = [
  {
    id: '1',
    supplierId: '1',
    category: 'fuel',
    description: 'Combustível - Janeiro 2024',
    amount: 1200,
    dueDate: '2024-02-05',
    status: 'paid',
    paymentDate: '2024-02-03',
    paymentMethod: 'pix',
    recurring: true,
    recurringFrequency: 'monthly',
  },
  {
    id: '2',
    supplierId: '2',
    category: 'maintenance',
    description: 'Manutenção preventiva - Gol ABC-1234',
    amount: 450,
    dueDate: '2024-02-10',
    status: 'pending',
    recurring: false,
  },
  {
    id: '3',
    category: 'salary',
    description: 'Salário - Carlos Eduardo Mendes',
    amount: 3500,
    dueDate: '2024-02-05',
    status: 'paid',
    paymentDate: '2024-02-05',
    paymentMethod: 'bank_transfer',
    recurring: true,
    recurringFrequency: 'monthly',
  },
  {
    id: '4',
    category: 'rent',
    description: 'Aluguel - Sede da Auto Escola',
    amount: 2800,
    dueDate: '2024-02-10',
    status: 'pending',
    recurring: true,
    recurringFrequency: 'monthly',
  },
  {
    id: '5',
    supplierId: '3',
    category: 'supplies',
    description: 'Material didático e papelaria',
    amount: 280,
    dueDate: '2024-02-15',
    status: 'overdue',
    recurring: false,
  },
];